version: '2.3'

services:
  java:
    image: openjdk:8-jdk
    working_dir: /work
    environment:
      - GRADLE_OPTS="-Dorg.gradle.daemon=false"
      - TERM="dumb"

    volumes:
      - ./:/work

  app:
    build:
      context: .
    working_dir: /opt/app
    environment:
      - GRADLE_OPTS="-Dorg.gradle.daemon=false"
      - TERM="dumb"
    ports:
      - "8080:8080"
    volumes:
      - ./:/work

  integ:
    image: openjdk:8-jdk
    working_dir: /work
    environment:
      - GRADLE_OPTS="-Dorg.gradle.daemon=false"
      - TERM="dumb"
    volumes:
      - ./:/work
    depends_on:
      - app
