version: '2.3'

services:
  java:
    image: openjdk:8-jdk
    working_dir: /work
    volumes:
      - ./:/work

  app:
    build:
      context: .
    working_dir: /opt/app
    ports:
      - "8080:8080"
    volumes:
      - ./:/work

  integ:
    image: openjdk:8-jdk
    working_dir: /work
    volumes:
      - ./:/work
    depends_on:
      - app
