steps:
  - name: ":truck: Publish JARs"
    command: .buildkite/pipeline-jar-cmd.sh
    plugins:
      docker-compose#v1.8.3:
        run: java
        environment:
          - BUILDKITE_BRANCH
          - BUILDKITE_BUILD_NUMBER
          - BUILDKITE_COMMIT
          - BUILDKITE_PIPELINE_DEFAULT_BRANCH
          - BUILDKITE_PULL_REQUEST
          - BUILDKITE_TAG
          - MAVEN_REPO_USER
          - MAVEN_REPO_PASS
